sudo: required
dist: trusty
services:
  - docker
  - neo4j

before_install:
##  - chmod +x .ci/docker-run.sh && bash .ci/docker-run.sh $IMAGE $NAME 3307 $OMIT_FEATURES
  - sudo docker run -d -p 3307:3307 mysql:8.0 -e MYSQL_ROOT_PASSWORD='test' -e MYSQL_DATABASE='homestead'
  - npm install
  - npm run dev

language: php

php:
  - 7.2

## Cache composer and vendor libraries
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php artisan key:generate
  - php artisan migrate
  - composer update --prefer-dist

script:
  #- phpunit --coverage-clover coverage.xml
  - phpunit

after_script:
  # upload coverage.xml file to Coveralls to analyze it
  # minimal required coverage is set to 80+ %
  # - wget https://github.com/satooshi/php-coveralls/releases/download/v2.1.0/coveralls.phar
  # - php coveralls.phar --verbose


notifications:
email: false
